#! /bin/bash

if [ $# -eq 0 ]; then # show help
    echo "Used to preprocss some file: like compile scss, cleanup html before reload browsers"
    exit 1
fi

# this script is runned with CWD = root param passed to http-watcher

notify_changed() {
    # ping server, server knows how to reload the file
    wget http://127.0.0.1:8000/dev/changed?f=$1 -O -
}

compile_scss() {
    sass -t compressed --cache-location /tmp $1 $2
}

compress_html() {
    java -jar thirdparty/htmlcompressor.jar \
        --type html \
        --charset utf8 \
        --remove-quotes  \
        --remove-script-attr \
        --remove-link-attr \
        --remove-style-attr \
        --simple-bool-attr \
        --remove-intertag-spaces $1 -o $2
}

# [event file] pairs are passed as command line args
while [ $# -ne 0 ]; do
    event=$1; shift             # event name
    file=$1; shift              # file name
    extention=${file##*.}       # file extension
    echo $file $event
    case $extention in
        scss) # compile scss to css
            mkdir -p public/css/
            for scss in $(find . -name "[^_]*.scss"); do
                name=$(basename $scss) # filename
                name="${name%.*}"      #  remove extension
                compile_scss $scss public/css/$name.css
            done
            ;;
        tpl) # compress the changed mustache template using htmlcompressor
            mkdir -p src/templates
            # compress files in templates to src/templates
            target=$(echo $file | sed -e 's/templates/src\/templates/')
            compress_html $file $target
            notify_changed $file
            ;;
        clj)
            notify_changed $file
            ;;
    esac
done

# For rssminer
# http-watcher -root ~/workspace/rssminer -ignores "test/,/\.,\.css$,.#,src/templates,target/,public/,android/" -proxy 9090 -command ./preprocess
